# Generated by Django 5.0.4 on 2024-04-04 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchstats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwatchtime',
            name='total_watch_time',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
